# Generated by Django 5.0.1 on 2024-01-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_genre_remove_artist_choices_remove_artist_song_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='email',
        ),
    ]
